### ISSUE TITLE
fn_initSpy.sqf Fehler

### ISSUE THREAD

**Issue by tobias231h** [TheTotenkopf/SealDrop-AltisLife-Script-Pack#6]
Hallo, in der Datei SpyGlass/fn_initSpy.sqf   fehlt ein Komma in Zeile 141:

...
"A3_Weapons_F_Mark","A3_Weapons_F_Mark_LongRangeRifles_DMR_02","A3_Weapons_F_Mark_LongRangeRifles_DMR_03","A3_Weapons_F_Mark_LongRangeRifles_DMR_04",
"A3_Weapons_F_Mark_LongRangeRifles_DMR_05","A3_Weapons_F_Mark_LongRangeRifles_DMR_06","A3_Weapons_F_Mark_Machineguns_MMG_01",
"A3_Weapons_F_Mark_Machineguns_MMG_02"
"A3_CargoPoses_F_Heli","A3_Soft_F_Heli_Crusher_UGV"

Wenn man dieses Komma setzt, wird man aber ständig vom Server gekickt.
Irgendwelche Lösungen?

**Comment by TheTotenkopf** [comment]
Der Fehler wurde behoben.. 

SpyGlass ist in der Vanilla Mission deaktiviert, man sollte nicht gekickt werden.

**Comment by tobias231h** [comment]
Leider werde ich immernoch gekickt von SpyGlass.
Das steht in der RPT:

"SPYGLASS-FLAG:NAME:SpielerID:Non_whitelisted_variable:life_fnc_onplayerkilled_meta:TYPE:CODE:NS:Mission"

"SPYGLASS-FLAG:NAME:SpielerID:Non_whitelisted_variable:life_fnc_licensecheck_meta:TYPE:CODE:NS:Mission"

**Comment by majoess** [comment]
Wie wäre es wenn du einfach SpyGlass ausschaltest?
